apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ns-killer
    namespace: ns-killer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "delete"]
