apiVersion: v1
kind: ConfigMap
metadata:
  name: ns-killer
  namespace: ns-killer
data:
  ns-killer.conf: |
    config:
      retention:
        kind: minutes
        time: 1
    namespace:
      include:
        - test
      exclude:
        - kube-system
        - kube-public
        - default
        - ingress-nginx
        - cert-manager
        - cattle-system
        - prometheus
        - jenkins
