apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-killer
  namespace: ns-killer
subjects:
  - kind: ServiceAccount
    name: ns-killer
    namespace: ns-killer
roleRef:
  kind: ClusterRole
  name: ns-killer
  apiGroup: rbac.authorization.k8s.io
