name: Build and publish Docker images

on: 
  workflow_dispatch:
    inputs:
      release:
        description: Release name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - 1.19.3
          - 1.18.10
          - 1.17.13
          - 1.16.15
          - 1.15.12
          - 1.14.10
          - 1.13.12
    steps:
      - uses: actions/checkout@v1

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          KUBECTL_VERSION: ${{ matrix.kubectl_version }}
        with:
          name: germainlefebvre4/ns-killer
          buildargs: KUBECTL_VERSION
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest-${{ matrix.kubectl_version }},latest-kubectl${{ matrix.kubectl_version }},${{ github.event.inputs.release }}-${{ matrix.kubectl_version }},${{ github.event.inputs.release }}-kubectl${{ matrix.kubectl_version }}"

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          repository: germainlefebvre4/ns-killer
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD2 }}
          readme-filepath: ./docs/dockerhub/README.md